{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: elasticsearch
spec:
  accessModes:
    - {{ .Values.elasticsearch.persistence.accessMode }}
  {{- if .Values.elasticsearch.persistence.storageClass }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        {{- include "bdsp-pipeline.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: sysctl
        image: busybox:1.35
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      securityContext:
        fsGroup: {{ .Values.elasticsearch.securityContext.fsGroup }}
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        env:
        - name: discovery.type
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: discovery.type
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ES_JAVA_OPTS
        - name: xpack.security.enabled
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: xpack.security.enabled
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          runAsUser: {{ .Values.elasticsearch.securityContext.runAsUser }}
          runAsNonRoot: {{ .Values.elasticsearch.securityContext.runAsNonRoot }}
        ports:
        - containerPort: {{ .Values.elasticsearch.service.httpPort }}
          name: http
        - containerPort: {{ .Values.elasticsearch.service.transportPort }}
          name: transport
        volumeMounts:
        - name: elasticsearch-storage
          mountPath: /usr/share/elasticsearch/data
        {{- if .Values.elasticsearch.resources }}
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.elasticsearch.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: {{ .Values.elasticsearch.service.httpPort }}
          initialDelaySeconds: {{ .Values.elasticsearch.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.elasticsearch.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.elasticsearch.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.elasticsearch.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: {{ .Values.elasticsearch.service.httpPort }}
          initialDelaySeconds: {{ .Values.elasticsearch.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.elasticsearch.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.elasticsearch.readinessProbe.timeoutSeconds }}
        {{- end }}
      volumes:
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.httpPort }}
    targetPort: {{ .Values.elasticsearch.service.httpPort }}
  - name: transport
    port: {{ .Values.elasticsearch.service.transportPort }}
    targetPort: {{ .Values.elasticsearch.service.transportPort }}
  type: {{ .Values.elasticsearch.service.type }}
{{- end }}
