{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: minio
spec:
  accessModes:
    - {{ .Values.minio.persistence.accessMode }}
  {{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        {{- include "bdsp-pipeline.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: minio
        image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
        imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_ROOT_PASSWORD
        command:
        - /bin/sh
        - -c
        - minio server /data --console-address ":9001"
        ports:
        - containerPort: {{ .Values.minio.service.apiPort }}
          name: api
        - containerPort: {{ .Values.minio.service.consolePort }}
          name: console
        volumeMounts:
        - name: minio-storage
          mountPath: /data
        {{- if .Values.minio.resources }}
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.minio.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: {{ .Values.minio.service.apiPort }}
          initialDelaySeconds: {{ .Values.minio.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.minio.livenessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.minio.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: {{ .Values.minio.service.apiPort }}
          initialDelaySeconds: {{ .Values.minio.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.minio.readinessProbe.periodSeconds }}
        {{- end }}
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: minio
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: {{ .Values.minio.service.apiPort }}
    targetPort: {{ .Values.minio.service.apiPort }}
  - name: console
    port: {{ .Values.minio.service.consolePort }}
    targetPort: {{ .Values.minio.service.consolePort }}
  type: {{ .Values.minio.service.type }}
{{- end }}
