{{- if .Values.mlflow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: mlflow
spec:
  replicas: {{ .Values.mlflow.replicaCount }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
        {{- include "bdsp-pipeline.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
          imagePullPolicy: {{ .Values.mlflow.image.pullPolicy }}
          # We map the secrets/configs from your existing services here
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: MINIO_ROOT_PASSWORD
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio:{{ .Values.minio.service.apiPort }}"
            - name: MLFLOW_S3_IGNORE_TLS
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              value: "$(MINIO_ACCESS_KEY)"
            - name: AWS_SECRET_ACCESS_KEY
              value: "$(MINIO_SECRET_KEY)"
            - name: MLFLOW_ARTIFACTS_DESTINATION
              value: "s3://{{ .Values.mlflow.defaultBucket }}/"
            # Construct the DB URI dynamically using the env vars above
            - name: MLFLOW_BACKEND_STORE_URI
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:{{ .Values.postgres.service.port }}/$(POSTGRES_DB)"
            - name: MLFLOW_PORT
              value: "{{ .Values.mlflow.service.port }}"
            - name: MLFLOW_HOST
              value: "0.0.0.0"
          
          # Replicating the docker-compose command. 
          # NOTE: In production, it is better to build a custom Docker image with these dependencies 
          # pre-installed to improve startup time and reliability.
          command:
            - /bin/bash
            - -c
            - |
              echo "Installing dependencies..."
              pip install --no-cache-dir psycopg2-binary boto3
              
              echo "Starting MLflow server..."
              mlflow server \
                --backend-store-uri "${MLFLOW_BACKEND_STORE_URI}" \
                --artifacts-destination "${MLFLOW_ARTIFACTS_DESTINATION}" \
                --host "${MLFLOW_HOST}" \
                --port "${MLFLOW_PORT}"
          
          ports:
            - name: http
              containerPort: {{ .Values.mlflow.service.port }}
              protocol: TCP
          
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60 # Increased to allow time for pip install
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            {{- toYaml .Values.mlflow.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: mlflow
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
    - port: {{ .Values.mlflow.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mlflow
{{- end }}