{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.config.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.config.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.config.database | quote }}
{{- end }}
---
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: minio
type: Opaque
stringData:
  root-user: {{ .Values.minio.config.rootUser | quote }}
  root-password: {{ .Values.minio.config.rootPassword | quote }}
{{- end }}
---
{{- if .Values.openmetadata.enabled }}
{{- if .Values.openmetadata.postgresMetadata.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-metadata-secret
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: postgres-metadata
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.openmetadata.postgresMetadata.config.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.openmetadata.postgresMetadata.config.password | quote }}
  POSTGRES_DB: {{ .Values.openmetadata.postgresMetadata.config.database | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.superset.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
  namespace: {{ include "bdsp-pipeline.namespace" . }}
  labels:
    {{- include "bdsp-pipeline.labels" . | nindent 4 }}
    app: superset
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.superset.config.adminPassword | quote }}
  SECRET_KEY: {{ .Values.superset.config.secretKey | quote }}
{{- end }}
