# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    order_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
    user_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
    status:
      type_snapshot:
        column_type: VARCHAR
        nullable: true
    gender:
      type_snapshot:
        column_type: VARCHAR
        nullable: true
    created_at:
      type_snapshot:
        column_type: VARCHAR
        nullable: true
    returned_at:
      type_snapshot:
        column_type: VARCHAR
        nullable: true
    shipped_at:
      type_snapshot:
        column_type: VARCHAR
        nullable: true
    delivered_at:
      type_snapshot:
        column_type: VARCHAR
        nullable: true
    num_of_item:
      type_snapshot:
        column_type: BIGINT
        nullable: true
  file_format:
    file_paths:
    - /dqo/data/orders.csv
