import time
import random
import clickhouse_connect
from datetime import datetime

# Connect to ClickHouse
client = clickhouse_connect.get_client(host='localhost', port=8123, username='admin', password='password123')

print("🚀 Starting mock data injection into ClickHouse...")

symbols = ['MSFT', 'NVDA']
base_prices = {'MSFT': 400, 'NVDA': 480}

try:
    while True:
        data = []
        for sym in symbols:
            # Create random price fluctuations (-1% to +1%)
            change = random.uniform(-0.01, 0.01)
            current_price = base_prices[sym] * (1 + change)
            base_prices[sym] = current_price # Update price for the next iteration
            
            # Create random volume
            volume = random.uniform(1000, 5000)
            
            # Add to insert list
            # Structure: [symbol, price, volume, timestamp]
            # timestamp generated by server (using now()) or passed in
            data.append([sym, round(current_price, 2), round(volume, 2), datetime.utcnow()])

        # Insert into ClickHouse
        client.insert('warehouse.stock_realtime', data, column_names=['symbol', 'price', 'volume', 'timestamp'])
        
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Pushed {len(data)} records...")
        
        # Sleep for 1 second (Simulate real-time)
        time.sleep(1)

except KeyboardInterrupt:
    print("\n🛑 Data injection stopped.")