kafka:
  brokers: "kafka-node-1:9092,kafka-node-1:9092,kafka-node-2:9092,kafka-node-3:9092,kafka-node-4:9092"
  topic: "event_streaming"

internal_database:
  username: postgres
  password: postgres
  database: internal_database
  host: internal_database
  port: 5432

airflow:
  username: admin
  password: admin
  url: http://webserver:8080